document.addEventListener('DOMContentLoaded',()=>{
  const screen=document.getElementById('envelopeScreen');
  const site=document.getElementById('siteContent');
  const open=document.getElementById('btnOpenEnvelope');
  if(open){open.addEventListener('click',()=>{screen.classList.add('is-opening');document.body.classList.remove('intro-locked');site.classList.add('is-visible');setTimeout(()=>screen.remove(),850);});}
  const wedding=new Date('2028-05-26T16:00:00+02:00').getTime();
  const pad=n=>String(Math.max(0,n)).padStart(2,'0');
  function countdown(){let d=wedding-Date.now();if(d<0)d=0;const days=Math.floor(d/86400000);d%=86400000;const hours=Math.floor(d/3600000);d%=3600000;const min=Math.floor(d/60000);const sec=Math.floor((d%60000)/1000);document.getElementById('cd-days').textContent=days;document.getElementById('cd-hours').textContent=pad(hours);document.getElementById('cd-minutes').textContent=pad(min);document.getElementById('cd-seconds').textContent=pad(sec)}countdown();setInterval(countdown,1000);
  const progress=document.getElementById('scrollProgress'); const top=document.getElementById('btnBackToTop');
  function scrollUI(){const h=document.documentElement.scrollHeight-innerHeight;const p=h>0?(scrollY/h)*100:0;progress.style.width=p+'%';progress.setAttribute('aria-valuenow',Math.round(p));top.classList.toggle('show',scrollY>500)}window.addEventListener('scroll',scrollUI,{passive:true});scrollUI();top.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
  const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
  document.querySelectorAll('.gallery-thumb').forEach(t=>{const show=()=>{const img=document.getElementById('lightboxImg');const cap=document.getElementById('lightboxCaption');img.src=t.dataset.imgSrc;cap.textContent=t.dataset.caption||'';bootstrap.Modal.getOrCreateInstance(document.getElementById('galleryModal')).show()};t.addEventListener('click',show);t.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}})});
  const yes=document.getElementById('presenceYes'),no=document.getElementById('presenceNo'),dy=document.getElementById('rsvpDetailsYes'),dn=document.getElementById('rsvpDetailsNo');function attendance(){dy.classList.toggle('d-none',!yes.checked);dn.classList.toggle('d-none',!no.checked)};[yes,no].forEach(x=>x&&x.addEventListener('change',attendance));
  const children=document.getElementById('childrenCount'),ages=document.getElementById('childrenAgesContainer');function childAges(){const n=Number(children.value);ages.classList.toggle('d-none',n===0);ages.innerHTML='';for(let i=1;i<=n;i++){const col=document.createElement('div');col.className='col-sm-6';col.innerHTML=`<label class="form-label" for="childAge${i}">Età bambino ${i}</label><input id="childAge${i}" name="eta_bambino_${i}" type="number" min="0" max="17" class="form-control" placeholder="Età">`;ages.appendChild(col)}}children&&children.addEventListener('change',childAges);
  const guests=document.getElementById('guestsContainer'),add=document.getElementById('btnAddGuest');let guestNo=0;add&&add.addEventListener('click',()=>{guestNo++;const div=document.createElement('div');div.className='row g-2 align-items-end mb-2 guest-row';div.innerHTML=`<div class="col-md-5"><label class="form-label">Ospite ${guestNo}</label><input class="form-control" name="ospite_${guestNo}" placeholder="Nome e Cognome"></div><div class="col-md-5"><label class="form-label">Esigenze alimentari</label><input class="form-control" name="dieta_${guestNo}" placeholder="Nessuna / vegetariano / allergie..."></div><div class="col-md-2"><button type="button" class="btn btn-custom-ghost w-100 remove-guest">Rimuovi</button></div>`;div.querySelector('.remove-guest').onclick=()=>div.remove();guests.appendChild(div)});
  document.getElementById('rsvpForm')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity()){form.classList.add('was-validated');return}document.getElementById('rsvpFeedback').classList.remove('d-none');form.reset();dy.classList.add('d-none');dn.classList.add('d-none');ages.classList.add('d-none');guests.innerHTML='';});
  document.getElementById('btnCopyIban')?.addEventListener('click',async()=>{const text=document.getElementById('ibanText').textContent.trim();try{await navigator.clipboard.writeText(text)}catch(e){}document.getElementById('copyText').textContent='Copiato';setTimeout(()=>document.getElementById('copyText').textContent='Copia IBAN',1800)});
});
